module.exports=[{
    "id":"0",
    "image":"https://i1.feedspot.com/200/4818273.jpg",
    "title":"The Bitcoin Forum",
    "info":"Bitcoin Forum general discussion about the Bitcoin ecosystem that doesn't fit better elsewhere.",
    "link":"https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=4818273&q=site:https%3A%2F%2Fforum.bitcoin.com%2Ffeed.php",
    "rating":"4"
},
{
    "id":"1",
    "image":"https://i1.feedspot.com/200/5281036.jpg?t=1621059711",
    "title":"Trendri ",
    "info":"Trendri is a make money forum for online money making. ",
    "link":"https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=5281036&q=site:https%3A%2F%2Fwww.trendri.com%2Fforums%2Fcryptocurrency%2Findex.rss",
    "rating":"4"
},
{   "id":"2",
    "image":"https://i1.feedspot.com/5171192.jpg?t=1594877591",
    "title":"Beer Money Forum",
    "info":"Latest news from the crypto world. Make a Profit from Buying / Selling coins.",
    "link":"https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=5171192&q=site:https%3A%2F%2Fwww.beermoneyforum.com%2Fforums%2Fcrypto-currencies.6%2Findex.rss",
    "rating":"4"
},
{   "id":"3",
    "image":"https://i1.feedspot.com/200/4973810.jpg?t=1597903678",
    "title":"Bitcoin Garden Forum",
    "info":"Bitcoin Garden Forum is a forum where all the bitcoin traders come together and discuss on the latest trends in the bitcoin world.",
    "link":"https://bitcoingarden.org/forum/index.php?board=4.0",
    "rating":"4"
},
{   "id":"4",
    "image":"https://i1.feedspot.com/200/4973530.jpg?t=1612944206",
    "title":" Dash Forum",
    "info":"This is the official Dash Cryptocurrency forum. Dash is digital cash designed to offer financial freedom to everyone.",
    "link":"https://www.dash.org/forum/",
    "rating":"4"
},
{   "id":"5",
    "image":"https://i1.feedspot.com/200/4973781.jpg?t=1604121471",
    "title":" Litecointalk",
    "info":"The forum is dedicated to discussions on Litecoin.",
    "link":"https://litecointalk.io/",
    "rating":"4"
},
{   "id":"6",
    "image":"https://i1.feedspot.com/4973779.jpg?t=1604478350",
    "title":" Hashgains",
    "info":"Welcome to Our bitcoin forum section, here you can find all answers related to altcoins and cyptocurrency.",
    "link":"https://www.hashgains.com/forums/",
    "rating":"4"
},
{   "id":"7",
    "image":"https://i1.feedspot.com/200/5171931.jpg?t=1611139807",
    "title":" Currency Times",
    "info":" Currency Times is the best stage to distribute and read most recent news about trending topics, blockchains, business world, and technology.",
    "link":"https://www.currencytimes.co.in/",
    "rating":"4"
},
{   "id":"8",
    "image":"https://i1.feedspot.com/4973529.jpg",
    "title":"Bitcoin For Beginners",
    "info":"Come join the best, beginner-friendly cryptocurrency forum and discussion board to ask questions about trading and talk Bitcoin, altcoins, and all things crypto.",
    "link":"https://www.bitcoinforbeginners.io/discussions/",
    "rating":"4"
},
{   "id":"9",
    "image":"https://i1.feedspot.com/200/5044928.jpg",
    "title":" Crypto Investor Pro",
    "info":" A team of cryptocurrency enthusiasts, blockchain technology supporters and investors, we aim to provide a steady stream of reliable information that will help you navigate the exciting world of cryptocurrency.",
    "link":"http://cryptoinvestorpro.com/",
    "rating":"4"
},
{   "id":"10",
    "image":"https://i1.feedspot.com/200/5281039.jpg?t=1621058709",
    "title":" CryptoFaucets Forum",
    "info":" CryptoFaucets Forum is a place to discuss and learn about Cryptocurrency and make money online.",
    "link":"https://www.cryptofaucets.org/forum/",
    "rating":"4"
},
]
