module.exports = [
  {
    id: "0",
    img: "https://nitrocdn.com/enRWBQfsbPPTeStgSQKbtHYPcuPDOirW/assets/static/optimized/rev-5898e00/wYiwMmE-qRT5aJ6c/w:234/h:234/q:74/https://cdn.aelieve.com/toptere/ImdbCom-Logo.png",
    title: "IMDB",
    info: "IMDb is an online database of information related to films, television series, home videos, video games, and streaming content online",
    link: "https://www.imdb.com/",
    rating: "4",
  },
  {
    id: "1",
    img: "https://nitrocdn.com/enRWBQfsbPPTeStgSQKbtHYPcuPDOirW/assets/static/optimized/rev-5898e00/wYiwMmE-3HUwseCf/w:234/h:234/q:74/https://cdn.aelieve.com/toptere/CnnCom-Logo.png",
    title: "Cnn",
    info: "The Cable News Network is a multinational news-based pay television channel headquartered in Atlanta, United States.",
    link: "https://edition.cnn.com/",
    rating: "4",
  },
  {
    id: "2",
    img: "https://nitrocdn.com/enRWBQfsbPPTeStgSQKbtHYPcuPDOirW/assets/static/optimized/rev-5898e00/wYiwMmE-3D_5Ce8X/w:234/h:234/q:74/https://cdn.aelieve.com/toptere/TwitchTv-Logo.png",
    title: "Twitch.tv",
    info: "Twitch is an American video live streaming service that focuses on video game live streaming, including broadcasts of esports competitions, in addition to offering music broadcasts, creative content, and streams.",
    link: "https://www.twitch.tv/",
    rating: "4",
  },
  {
    id: "3",
    img: "https://nitrocdn.com/enRWBQfsbPPTeStgSQKbtHYPcuPDOirW/assets/static/optimized/rev-5898e00/wYiwMmE-wj8Ofjhg/w:234/h:234/q:74/https://cdn.aelieve.com/toptere/Bbc.jpg",
    title: "Bbc.com",
    info: "Breaking news, sport, TV, radio and a whole lot more. The BBC informs, educates and entertains - wherever you are, whatever your age.",
    link: "https://bbc.com/",
    rating: "4",
  },
  {
    id: "4",
    img: "https://nitrocdn.com/enRWBQfsbPPTeStgSQKbtHYPcuPDOirW/assets/static/optimized/rev-5898e00/wYiwMmE-s3nxVgWu/w:234/h:234/q:74/https://cdn.aelieve.com/toptere/SoundcloudCom-Logo.png",
    title: "Soundcloud.com",
    info: "Discover and play over 265 million music tracks. Join the world's largest online community of artists, bands, DJs, and audio creators.",
    link: "https://soundcloud.com/",
    rating: "4",
  },
  {
    id: "5",
    img: "https://nitrocdn.com/enRWBQfsbPPTeStgSQKbtHYPcuPDOirW/assets/static/optimized/rev-5898e00/wYiwMmE-uCnOs8QR/w:234/h:234/q:74/https://cdn.aelieve.com/toptere/EtsyCom-Logo.png",
    title: "Etsy.com",
    info: "Etsy is a global online marketplace, where people come together to make, sell, buy, and collect unique items. ",
    link: "https://www.etsy.com/",
    rating: "4",
  },
  {
    id: "6",
    img: "https://nitrocdn.com/enRWBQfsbPPTeStgSQKbtHYPcuPDOirW/assets/static/optimized/rev-5898e00/wYiwMmE-pb-eBC0c/w:234/h:234/q:74/https://cdn.aelieve.com/toptere/Azlyrics.jpg",
    title: "AZlyrics.com",
    info: "It's a place where all searches end! We have a large, legal, every day growing universe of lyrics where stars of all genres and ages ",
    link: "https://www.azlyrics.com/",
    rating: "4",
  },
  {
    id: "7",
    img: "https://nitrocdn.com/enRWBQfsbPPTeStgSQKbtHYPcuPDOirW/assets/static/optimized/rev-5898e00/wYiwMmE-QdmT7R3B/w:234/h:234/q:74/https://cdn.aelieve.com/toptere/Foxnews.jpg",
    title: "Foxnews.com",
    info: "Breaking News, Latest News and Current News from FOXNews.com.  ",
    link: "https://www.foxnews.com/",
    rating: "4",
  },
  {
    id: "8",
    img: "https://nitrocdn.com/enRWBQfsbPPTeStgSQKbtHYPcuPDOirW/assets/static/optimized/rev-5898e00/wYiwMmE-nVmpLKxT/w:234/h:234/q:74/https://cdn.aelieve.com/toptere/DeviantartCom-Logo.png",
    title: "Deviantart.com",
    info: "DeviantArt is an American online art community featuring artwork, videography and photography subsidiary of the Israeli company Wix.com. ",
    link: "https://www.deviantart.com/",
    rating: "4",
  },
  {
    id: "9",
    img: "https://nitrocdn.com/enRWBQfsbPPTeStgSQKbtHYPcuPDOirW/assets/static/optimized/rev-5898e00/wYiwMmE-H-7hSHto/w:234/h:234/q:74/https://cdn.aelieve.com/toptere/Foodnetwork.jpg",
    title: "Foodnetwork.com",
    info: "Food Network is an American basic cable channel owned by Television Food Network, G.P., a joint venture and general partnership between Discovery, Inc. and Nexstar Media Group. ",
    link: "https://foodnetwork.com/",
    rating: "4",
  },
];
