module.exports=[{
    "id":"0",
    "img":"https://images.everydayhealth.com/images/healthy-living/fitness/all-about-yoga-mega-722x406.jpg",
    "title":"Global Yoga Community",
    "info":"Yoga is much more than physical exercise. It can be your path to a more relaxed, centered, fulfilling lifestyle.",
    "link":"https://www.facebook.com/groups/globalyogacommunity/",
    "rating":"4"
},
{
    "id":"1",
    "img":"https://ewscripps.brightspotcdn.com/5c/4f/00e9b88c43f8a28e11a7c80204a9/rona-generic-2.jpg",
    "title":"RHIhub",
    "info":"Information on vaccine planning, administration, storage and handling, and more. Includes clinical information for each COVID-19 vaccine.",
    "link":"https://www.ruralhealthinfo.org/topics/covid-19/vaccination",
    "rating":"4"
},
{   "id":"2",
    "img":"https://thumbs.dreamstime.com/b/community-heart-word-cloud-marker-social-concept-197980967.jpg",
    "title":"Medline Plus",
    "info":"Heart disease is the leading cause of the death in the United States. It is also a major cause of disability.",
    "link":"https://medlineplus.gov/howtopreventheartdisease.html",
    "rating":"4"
},
{   "id":"3",
    "img":"https://www.news-medical.net/image.axd?picture=2020%2F4%2Fshutterstock_571889917.jpg",
    "title":"Centers For Disease Control and Prevention",
    "info":"Community-based organizations (CBOs), faith-based organizations (FBOs), community health workers (CHWs), and other community groups can take an active role in helping people at risk for type 2 diabetes, people with diabetes, and their families build healthier lives and reduce their risk.",
    "link":"https://www.cdc.gov/diabetes/professional-info/community-organizations.html",
    "rating":"4"
},
{   "id":"4",
    "img":"https://www.narayanahealth.org/blog/wp-content/uploads/2019/06/shutterstock_198680741.jpg",
    "title":"Centers For Disease Control and Prevention",
    "info":"Lung diseases are some of the most common medical conditions in the world.",
    "link":"https://www.lung.org/",
    "rating":"4"
},
{   "id":"5",
    "img":"https://image.shutterstock.com/image-vector/womens-health-vector-illustration-word-260nw-1824798584.jpg",
    "title":"National Library Of Medicine",
    "info":"Women's health is a community issue",
    "link":"https://pubmed.ncbi.nlm.nih.gov/12292725/",
    "rating":"4"
},
{   "id":"6",
    "img":"https://www.thearthritisconnection.com/.image/t_share/MTgwNjIxMzk1MTM3NDA2MDQw/arthritisresource.jpg",
    "title":"Arthritis Foundation",
    "info":"Learn strategies to reduce arthritis-related fatigue and boost your energy.",
    "link":"https://www.arthritis.org/",
    "rating":"4"
},
{   "id":"7",
    "img":"https://s3-eu-west-1.amazonaws.com/nusdigital/image/images/275900/original/MH_logo.jpg",
    "title":"Very Well Mind",
    "info":" Advocating for mental illness and giving back to the mental health community can be extremely powerful for both families and patients.",
    "link":"https://www.verywellmind.com/leading-mental-health-charities-and-organizations-4147842",
    "rating":"4"
},
{   "id":"8",
    "img":"https://image.shutterstock.com/image-photo/young-preganant-woman-expecting-baby-260nw-639846469.jpg",
    "title":"NCBI",
    "info":" Pregnancy, Childbirth, Postpartum and Newborn Care: A Guide for Essential Practice.",
    "link":"https://www.ncbi.nlm.nih.gov/books/NBK326675/",
    "rating":"4"
},
{   "id":"9",
    "img":"https://nationaltoday.com/wp-content/uploads/2020/10/Metastatic-Breast-Cancer-Awareness-Day-1.jpg",
    "title":"Cancer.Net",
    "info":" For many people with cancer, connecting with others provides emotional support and inspiration during a challenging time",
    "link":"https://www.cancer.net/coping-with-cancer/finding-social-support-and-information/online-communities-support",
    "rating":"4"
},
{   "id":"10",
    "img":"https://images.squarespace-cdn.com/content/v1/5a15ac3bd74cff5c36deac5c/1594141991667-IOMMSZTRQINQJNQ604LY/phobia+and+mental+health.jpg",
    "title":"NCBI",
    "info":" Anxiety disorders are among the most prevalent mental disorders, but the subcategory of specific phobias has not been well studied.",
    "link":"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7233312/",
    "rating":"4"
},
]
