module.exports = [{
"id":"0",    
"img": "https://res.cloudinary.com/practicaldev/image/fetch/s--RIBRi0-i--/c_fill,f_auto,fl_progressive,h_320,q_auto,w_320/https://dev-to-uploads.s3.amazonaws.com/uploads/organization/profile_image/4449/3da2c231-55bb-44a4-8e66-45e793742e9d.jpg",
"title": "Community Classroom",
"info": "The organisation is founded by Kunal Kushwaha. This community provide hands-on training, mentorship for FREE and have an inclusive community.Here, one can get expert guidance with career, Open Source, and internships, jobs around the world.",
"link": "https://www.commclassroom.org/",
"rating": "4"
},
{
"id":"1",
"img": "https://codeforcause.org/static/home/codeforcause.svg",
"title": "Code for cause",
"info": "An initiative to contribute to the Open Source community by providing training, guidance, and awareness about the possibilities in the field of software to students & professionals.",
"link": "https://codeforcause.org/",
"rating": "2"
},
{
"id":"3",    
"img": "google.com ",
"info": "Build projects, practice and learn to code from scratch - without leaving your browser.",
"link": "https://codedamn.com/",
"rating": "3"
},
{"id":"4",
"img": "https://dscfau.com/static/media/logo.ade0843b.png",
"title": "Developer Student Clubs",
"info": "Developer Student Clubs for students involved in Google Developer Technology are university-based community organizations.",
"link": "https://developers.google.com/community/gdsc",
"rating": "2"
},
{"id":"5",
"img": "https://gssoc.girlscript.tech/images/favicon/favicon.png",
"title": "Girl Script",
"info": "GirlScript is a section-8 NON PROFIT company registered under the government of India on the 2nd of June, 2017. GirlScript is open for all organisation and supports beginners in technology and programming. It supports diversity by reserving 50% seats for women & IGBT in all it's programs worldwide.",
"link": "https://www.girlscript.tech/home",
"rating": "2"
},
{"id":"6",
"img": "https://fossunited.org//files/fu.png",
"title": "FOSS United Foundation",
"info": "FOSS United Foundation is a registered non-profit founded in 2020, dedicated to the cause of building Free and Open Source (FOSS) projects and communities in India and elsewhere.",
"link": "https://fossunited.org/",
"rating": "2"
},
{"id":"7",
"img": "https://cdn.filestackcontent.com/RHJzJuTZQkSwIyQZO226",
"title": "Women who code",
"info": "A community focused on empowering women in technology, Women Who Code was established in 2011 and now has 230,000 members across 122 countries",
"link": "https://www.womenwhocode.com/",
"rating": "2"
},
{"id":"8",
"img": "https://img.etimg.com/photo/msid-64221161,quality-100/brandwire_image_45128030.jpg",
"title": "TechGig",
"info": "TechGig is a culmination of everything related to technology. TechGig is, a platform exclusively for IT professionals to synergize, share, exchange ideas, facts and information as well as showcase their work and express their views on the vast repertoire that the IT industry encompasses. Garnering cutting-edge insights, jobs, reviews and news, as well as providing a platform for connecting with colleagues and peers are the mainstay of TechGig.",
"link": "https://www.techgig.com/",
"rating": "2"
},
{"id":"9",
"img": "https://lh6.googleusercontent.com/qnuJPqY7MiGth7B2TcDbsH2Ge2y0rcQz2wkHXtKbg0b92gS7m3jqBXMnl4ySgBAwUjbCC7mo8NoIYnzQL1kmhh-80971eTCsxaMk-6xGrMAEgC6NuYdumSBUqosxe1kdUdxYSCM3",
"title": "Stack overflow",
"info": "For developers to learn, share their expertise, and build their careers, Stack Overflow is the biggest, most trusted online community.",
"link": "https://stackoverflow.com/",
"rating": "2"
},
{"id":"10",
"img": "https://cdn.hashnode.com/res/hashnode/image/upload/v1611244244346/Y0nrI4kKp.png?auto=compress&w=500",
"title": "Hashnode",
"info": "Hashnode enables developers from all over the world to connect and share ideas..",
"link": "https://hashnode.com/",
"rating": "2"
},
{"id":"11",
"img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Octicons-mark-github.svg/2048px-Octicons-mark-github.svg.png",
"title": "GitHub",
"info": "On GitHub, programmers can share their code and collaborate on projects together. ",
"link": "https://github.com/",
"rating": "2"
},
{"id":"12",
"img": "https://pbs.twimg.com/profile_images/1278218742158315520/hUY10gcw_400x400.jpg",
"title": "Women Tech network",
"info": "The WomenTech Network is a global forum to foster diversity in technology, leadership, and entrepreneurship, powered by Coding Children, Tech Family Projects, and Tallocate.",
"link": "https://www.womentech.net/en-in",
"rating": "2"
},
{"id":"13",
"img": "https://d21hwc2yj2s6ok.cloudfront.net/assets/networks/303/avatar/3a2534f51d0023372101f33c0e6cd63a-large.?1611940895",
"title": "Rewriting The Code (RTC)",
"info": "Founded by Sue Harnett, it is a community that aims to empower women in the field of technology through educational resources, mentorship, and industry experience.",
"link": "https://rewritingthecode.org/",
"rating": "2"
},
{"id":"14",
"img": "https://d1yjjnpx0p53s8.cloudfront.net/styles/logo-thumbnail/s3/092014/coderwall.png?itok=QHsi4eck",
"title": "Coderwall",
"info": "Another diverse and varied group that spans the whole spectrum of web creation is Coderwall. To help solve problems or learn new things for both beginners as well as more seasoned coders, it has a detailed “Tips” section. ",
"link": "https://coderwall.com/",
"rating": "2"
},
{"id":"15",
"img": "https://www.analyticsvidhya.com/wp-content/uploads/2015/06/kaggle-logo-transparent-300.png",
"title": "Kaggle",
"info": "Kaggle is an online community of data scientists and machine learning practitioners having over 19,000 public datasets and 200,000 open notebooks with a large repository of community published data and code. ",
"link": "https://www.kaggle.com/",
"rating": "2"
},
{"id":"16",
"img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI8cKqGCv43m_OZ6T_fia3Qb_CvGvjNhB_yRF5jZPV4CFS5TDpFROEn_UQz8-ZnaDAa7E&usqp=CAU",
"title": "SAP Community Network",
"info": "If you are a programmer who wants to get started with Business Coding, SAP Community Network is the right place for you! ",
"link": "https://community.sap.com/",
"rating": "2"
}
]